
export const callHistory = [
  { id: 1, type: 'Incoming', contact: 'Unknown', duration: '5:21', date: '2024-07-28', risk: 'high', emotion: 'Threatening', transcript: "Speaker1: Ma'am, I am calling from your bank's KYC department. Your account will be blocked if you do not update your PAN card details immediately. Speaker2: Oh my! But I just did this last month. Are you sure? Speaker1: Yes ma'am, it is a new RBI mandate. To avoid suspension, you must click the link I just sent you via SMS and enter your details. It is very urgent. Speaker2: A link via SMS? My bank always says never to click such links. This sounds suspicious. Speaker1: Ma'am, this is a secure portal! Your account will be frozen in 10 minutes if you don't comply. Do you want to lose access to all your money? Think of the trouble! Speaker2: My phone is giving me a scam alert... I am not comfortable with this. I will visit the branch tomorrow. Speaker1: There is no time for that! You must do it now! This is your final warning!", voice: 'algenib' },
  { id: 2, type: 'Incoming', contact: 'Aarav (Son)', duration: '3:15', date: '2024-07-28', risk: 'high', emotion: 'Stressed', transcript: "Aarav (Scammer): [Voice trembling] “Mom… it’s me, Aarav. Please don’t panic… I’ve had an accident.”\nMrs. Mehta: “Oh my God! Aarav, are you alright? Where are you?”\nAarav (Scammer): “I’m in the hospital. They won’t treat me unless I pay the admission fee… ₹50,000 right now. Please, Mom, I’m scared.”\nMrs. Mehta: “But… your phone sounds different.”\nAarav (Scammer): “It’s the hospital’s phone. Mom, there’s no time, please transfer the money to this account immediately. I’ll explain later.”", voice: 'achernar' },
  { id: 3, type: 'Incoming', contact: 'Rohit (Friend)', duration: '2:50', date: '2024-07-27', risk: 'medium', emotion: 'Stressed', transcript: "Rohit (Scammer): “Hey Aruna, it’s Rohit. Listen, I’m in a bit of a mess.”\nAruna: “Hey… you sound stressed. What happened?”\nRohit (Scammer): “I’m stuck at a petrol pump, my wallet’s gone, and my card isn’t working. Can you send me ₹5,000 right now? I’ll pay you back tomorrow, promise.”\nAruna: “Why don’t you use Paytm from your phone?”\nRohit (Scammer): “My battery’s about to die. Please just transfer to this number, it’s my friend’s account. I’m running out of time.”", voice: 'gacrux' },
  { id: 4, type: 'Incoming', contact: 'Ravi (Brother)', duration: '4:30', date: '2024-07-26', risk: 'low', emotion: 'Happy', transcript: 'Ravi: "Hey Aruna, kemon acho? (How are you?) I haven\'t seen you around Patia lately."\nAruna: "Bhalo, Ravi. Ami thik achi. (I\'m fine, Ravi). I was visiting my cousins in Cuttack for a few days." \nRavi: "Oh, Cuttack e? Kemon laglo? (Oh, in Cuttack? How was it?)"\nAruna: "It was good, nice to get away for a bit. We went to Barabati fort, and had some delicious Dahi Bara. You know, the usual touristy stuff."\nRavi: "Dahi Bara! I love that! You should have brought some back for me." laughs\nAruna: "Next time, promise! So, what\'s new with you? Anything interesting happening in Patia?"\nRavi: "Not much, just the usual. College is keeping me busy. By the way, have you heard about the new cafe that opened near KIIT gate? The one with the cool graffiti."\nAruna: "No way! I haven\'t seen it. Is it any good?"\nRavi: "Yeah, I went there with some friends last week. The coffee is decent and the ambiance is pretty chill. We should check it out sometime."\nAruna: "Definitely! I\'m free next week, maybe Tuesday?"\nRavi: "Tuesday works for me. Let\'s meet there around 4pm?"\nAruna: "Perfect! Okay, I\'ll see you then. Chai peeyenge (we\'ll have tea)?"\nRavi: "Chai toh banta hai! (Tea is a must!) Alright, see you on Tuesday then."\nAruna: "Okay, bye!"\nRavi: "Bye!"', voice: 'vindemiatrix' },
  { id: 5, type: 'Incoming', contact: 'Rishab (Husband)', duration: '8:45', date: '2024-07-26', risk: 'high', emotion: 'Threatening', transcript: "Emily (Scammer): “Hi honey, it’s me. I’m in a real jam.”\nMrs. Mehta: “Rishab? You sound strange. Is everything okay?”\nEmily (Scammer): “I’m in Mumbai for that conference, and my wallet was stolen with all my cards. I need you to wire me $500 for the hotel and a flight back.”\nMrs. Mehta: “Stolen? Oh no! But why $500? Can’t you call the bank?”\nEmily (Scammer): “It’s a long story, I don’t have time. The hotel is threatening to call the police if I don’t pay up now. Please, just send it to this account. It’s a colleague’s. I need you.”", voice: 'zubenelgenubi' },
  { id: 6, 'type': 'Incoming', 'contact': 'Pizza Delivery', duration: '2:15', date: '2024-07-25', risk: 'low', emotion: 'Casual', transcript: "Rahul: Hello! Thank you for calling Hot Slice Pizza, this is Rahul speaking. How can I help you today? \nAruna: Hi Rahul, I’d like to order a large Margherita pizza with extra cheese, please. \nRahul: Sure! Would you like a thin crust or regular crust? \nAruna: Let’s go with thin crust. Also, can you add some olives on top? \nRahul: Absolutely. So that’s one large thin crust Margherita with extra cheese and olives. Would you like any drinks or sides with that? \nAruna: Yes, a bottle of Coke, please. \nRahul: Got it. The total comes to ₹589. Can I have your delivery address? \nAruna: Yes, it’s Flat 302, Green Park Apartments, near City Mall. \nRahul: Perfect. Your order will be delivered in about 30–35 minutes. Payment will be on delivery, correct? \nAruna: Yes, cash on delivery. \nRahul: Great! Thank you for choosing Hot Slice Pizza, Aruna. Have a cheesy day! \nAruna: (laughs) Thanks, you too. Bye!", voice: 'callirrhoe' },
  { id: 7, type: 'Incoming', contact: 'Spam Caller', duration: '1:45', date: '2024-07-25', risk: 'high', emotion: 'Threatening', transcript: "Vendor Rep (Scammer): “Good afternoon, Professor Aruna. This is Anita from TechServe Solutions. We’re processing your last invoice for the NVIDIA server units. However, our bank account has changed due to an audit. Please update your records to the new account and confirm payment by tomorrow to avoid delivery delays.”\nAruna: “Changed your bank account? That's unusual. We have a process for vendor detail changes that requires official documentation on your company's letterhead. Can you please email that to the procurement department?”\nVendor Rep (Scammer): “Ma'am, the finance head insisted we call and confirm directly to expedite the process. The payment is for ₹5,00,000, and any delay will postpone the server delivery for the new lab by weeks.”\nAruna: “I understand the urgency, but I cannot bypass university protocol. I will check my email for the official notice and forward it to procurement. I will not be proceeding based on a phone call. Thank you.”", voice: 'laomedeia' },
  { id: 8, 'type': 'Incoming', 'contact': 'Sunita Mehta', duration: '2:55', date: '2024-07-24', risk: 'low', emotion: 'Loving', transcript: "Aruna: Hi, Maa! How are you today? \nSunita Mehta: Aruna! I’m fine, beta. Just finished my tea. I was thinking of you, so I called. How’s work at KIIT? \nAruna: Busy as always. I had back-to-back lectures today, and the final-year students are preparing for their project submissions. \nSunita Mehta: Ah, the same story every year. Are you taking care of your health? You sound a little tired. \nAruna: Yes, Maa, don’t worry. Rishab made lemon ginger tea for me this morning, so I’m okay. \nSunita Mehta: Good, good. And how’s Aarav? \nAruna: Oh, he’s busy coding as usual. I think he’s planning to build some AI tool for his class assignment. \nSunita Mehta: Just like his mother! Smart and hardworking. Tell him not to skip meals. \nAruna: I will, Maa. By the way, I’m thinking of visiting you next weekend. We can cook together like old times. \nSunita Mehta: That would be wonderful. I’ll make your favorite aloo paratha. \nAruna: Perfect! Okay, Maa, I have to get ready for my evening lecture. I’ll call you again tomorrow. \nSunita Mehta: Alright, beta. Take care. Love you. \nAruna: Love you too, Maa. Bye.", voice: 'maia' },
];

export const callDescriptions: { [key: number]: string } = {
    1: "A classic KYC (Know Your Customer) scam where the caller impersonates a bank official to create urgency and steal personal information via a phishing link.",
    2: "A sophisticated voice cloning scam where the scammer uses the cloned voice of Aruna's son, Aarav, to feign an emergency and request immediate funds.",
    3: "An impersonation scam where the caller pretends to be Aruna's friend, Rohit, who is in a fabricated emergency situation requiring urgent financial help.",
    4: "A casual, low-risk conversation between Aruna and her brother, Ravi, catching up and making plans to meet.",
    5: "A romance scam scenario where a scammer uses a cloned voice of an online partner to manipulate the victim into sending money for a travel ticket.",
    6: "A standard, legitimate service call for ordering a pizza. This call serves as a baseline for normal, low-risk interactions.",
    7: "A targeted spear-phishing attempt where a scammer impersonates a known vendor to intercept a large payment by providing fake bank details.",
    8: "A warm, personal call between Aruna and her mother, Sunita. This is another example of a safe, low-risk conversation."
};
